## Module manifest for module 'JAMF.Pro.PS5.1'
#
# Generated by: Mike Kelly
#
# Generated on: 08/31/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './JAMF.Pro.PS5.1.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b62b963d-50a8-42c8-99ca-6d602cfddbd8'

# Author of this module
Author = 'Mike Kelly'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '2024'

# Description of the functionality provided by this module
Description = 'This is a powershell module for JAMF Pro API'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('*')

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @('Microsoft.Graph.Intune')
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.0: Initial version
'@
    } # End of PSData hashtable

} # End of PrivateData hashtable
}
